const R2_PUBLIC_URL = "https://pub-196ffc8ef6544a1a83073be29e5a331f.r2.dev";

const fiestas = [

    {
        nombre: "DSM",
        lugar: "Sala Doppler, Vigo",
        carpeta: "DOPPLER_dsm_14_05_26",
        fotos: [
            "04e9d9d5-642f-48ec-938a-62d260dcc864.jpg",
            "3efe22c4-cc1a-45aa-b4be-5269de74af91.jpg",
            "4e364a76-2f6c-4397-bc16-e56114bc03ab.jpg",
            "661db00d-c1a9-4759-a4e2-3baaa72b1bbb.jpg",
            "75202f8e-c5ae-4e60-9b12-efdedbf8b2a9.jpg",
            "81cecab2-7cca-421c-9fe9-a010f5986f16.jpg",
            "87bedb06-3542-4ba0-85da-26eed2c41f02.jpeg",
            "87bedb06-3542-4ba0-85da-26eed2c41f02.jpg",
            "8d460d90-c6ae-4815-b1f3-c38ef859565d.jpg",
            "B93F7863-E135-431D-A5CC-2A1B02C75989.jpg",
            "IMG_0335.JPG",
            "IMG_0337.JPG",
            "IMG_0339.JPG",
            "IMG_0470.jpg",
            "IMG_1326.jpg",
            "IMG_1986.JPG",
            "IMG_1987.JPG",
            "IMG_4182.jpeg",
            "IMG_4187.jpeg",
            "IMG_4194.jpeg",
            "IMG_4224.jpeg",
            "IMG_4225.jpeg",
            "IMG_4233.jpeg",
            "IMG_4235.jpeg",
            "IMG_4241.jpeg",
            "IMG_4251.jpeg",
            "IMG_4253.jpeg",
            "IMG_4270.jpeg",
            "IMG_4281.jpeg",
            "IMG_4284.jpeg",
            "IMG_4285.jpeg",
            "IMG_4287.jpeg",
            "IMG_4288.jpeg",
            "IMG_4306.jpeg",
            "IMG_4309.jpeg",
            "IMG_4311.jpeg",
            "IMG_4318.jpeg",
            "IMG_4320.jpeg",
            "IMG_4322.jpeg",
            "IMG_4327.jpeg",
            "IMG_4342.jpeg",
            "IMG_4343.jpeg",
            "IMG_4344.jpeg",
            "IMG_4348.jpeg",
            "IMG_4360.jpeg",
            "IMG_4362.jpeg",
            "IMG_4368.jpeg",
            "IMG_4371.jpeg",
            "IMG_4402.jpeg",
            "IMG_4418.jpeg",
            "IMG_4424.jpeg",
            "IMG_4426.jpeg",
            "IMG_4427.jpeg",
            "IMG_4430.jpeg",
            "IMG_4436.jpeg",
            "IMG_4448.jpeg",
            "IMG_4451.jpeg",
            "IMG_4457.jpeg",
            "IMG_4458.jpeg",
            "IMG_4464.jpeg",
            "IMG_4467.jpeg",
            "IMG_4471.jpeg",
            "IMG_4472.jpeg",
            "IMG_4514.jpeg",
            "IMG_4521.jpeg",
            "a616304b-99dd-4bf1-b6cd-1336bff6b1e8.jpeg",
            "abcb075e-9d30-4eec-8d2b-73426ff6b088.jpg",
            "ba581f47-e173-4bfd-b04c-4c7d5288a20a.jpg",
            "c473c008-c89f-4a9d-9977-7b8607c9762d.jpg",
            "d3328734-e957-4084-9205-16a6c218750f.jpg",
            "fe22e847-ad45-479c-bd00-4c72dc1e8705.jpg",
        ]
    },
    {
        nombre: "MAIN COSTA",
        lugar: "Sala Doppler, Vigo",
        carpeta: "DOPPLER_main_costa_13_06_26",
        fotos: [
            "Monocromatics Doppler0.jpg",
            "Monocromatics Doppler1.jpg",
            "Monocromatics Doppler10.jpg",
            "Monocromatics Doppler11.jpg",
            "Monocromatics Doppler12.jpg",
            "Monocromatics Doppler13.jpg",
            "Monocromatics Doppler14.jpg",
            "Monocromatics Doppler15.jpg",
            "Monocromatics Doppler16.jpg",
            "Monocromatics Doppler17.jpg",
            "Monocromatics Doppler18.jpg",
            "Monocromatics Doppler19.jpg",
            "Monocromatics Doppler2.jpg",
            "Monocromatics Doppler20.jpg",
            "Monocromatics Doppler21.jpg",
            "Monocromatics Doppler22.jpg",
            "Monocromatics Doppler23.jpg",
            "Monocromatics Doppler24.jpg",
            "Monocromatics Doppler25.jpg",
            "Monocromatics Doppler26.jpg",
            "Monocromatics Doppler27.jpg",
            "Monocromatics Doppler28.jpg",
            "Monocromatics Doppler29.jpg",
            "Monocromatics Doppler3.jpg",
            "Monocromatics Doppler30.jpg",
            "Monocromatics Doppler31.jpg",
            "Monocromatics Doppler32.jpg",
            "Monocromatics Doppler33.jpg",
            "Monocromatics Doppler34.jpg",
            "Monocromatics Doppler35.jpg",
            "Monocromatics Doppler36.jpg",
            "Monocromatics Doppler37.jpg",
            "Monocromatics Doppler38.jpg",
            "Monocromatics Doppler39.jpg",
            "Monocromatics Doppler4.jpg",
            "Monocromatics Doppler40.jpg",
            "Monocromatics Doppler41.jpg",
            "Monocromatics Doppler42.jpg",
            "Monocromatics Doppler43.jpg",
            "Monocromatics Doppler44.jpg",
            "Monocromatics Doppler45.jpg",
            "Monocromatics Doppler46.jpg",
            "Monocromatics Doppler47.jpg",
            "Monocromatics Doppler48.jpg",
            "Monocromatics Doppler49.jpg",
            "Monocromatics Doppler5.jpg",
            "Monocromatics Doppler50.jpg",
            "Monocromatics Doppler51.jpg",
            "Monocromatics Doppler52.jpg",
            "Monocromatics Doppler53.jpg",
            "Monocromatics Doppler54.jpg",
            "Monocromatics Doppler55.jpg",
            "Monocromatics Doppler56.jpg",
            "Monocromatics Doppler57.jpg",
            "Monocromatics Doppler58.jpg",
            "Monocromatics Doppler59.jpg",
            "Monocromatics Doppler6.jpg",
            "Monocromatics Doppler60.jpg",
            "Monocromatics Doppler61.jpg",
            "Monocromatics Doppler62.jpg",
            "Monocromatics Doppler63.jpg",
            "Monocromatics Doppler64.jpg",
            "Monocromatics Doppler65.jpg",
            "Monocromatics Doppler66.jpg",
            "Monocromatics Doppler67.jpg",
            "Monocromatics Doppler68.jpg",
            "Monocromatics Doppler69.jpg",
            "Monocromatics Doppler7.jpg",
            "Monocromatics Doppler70.jpg",
            "Monocromatics Doppler71.jpg",
            "Monocromatics Doppler72.jpg",
            "Monocromatics Doppler73.jpg",
            "Monocromatics Doppler74.jpg",
            "Monocromatics Doppler75.jpg",
            "Monocromatics Doppler76.jpg",
            "Monocromatics Doppler77.jpg",
            "Monocromatics Doppler78.jpg",
            "Monocromatics Doppler79.jpg",
            "Monocromatics Doppler8.jpg",
            "Monocromatics Doppler80.jpg",
            "Monocromatics Doppler81.jpg",
            "Monocromatics Doppler82.jpg",
            "Monocromatics Doppler83.jpg",
            "Monocromatics Doppler84.jpg",
            "Monocromatics Doppler85.jpg",
            "Monocromatics Doppler86.jpg",
            "Monocromatics Doppler87.jpg",
            "Monocromatics Doppler88.jpg",
            "Monocromatics Doppler89.jpg",
            "Monocromatics Doppler9.jpg",
            "Monocromatics Doppler90.jpg",
            "Monocromatics Doppler92.jpg",
            "Monocromatics Doppler93.jpg",
        ]
    },
    {
        nombre: "YUNG BRANDY",
        lugar: "MyClub, Santiago",
        carpeta: "MYCLUB_blinblin_yung_brandy_13_05_26",
        fotos: [
            "BLIBLINXMONOCROMO1.jpg",
            "BLIBLINXMONOCROMO100.jpg",
            "BLIBLINXMONOCROMO101.jpg",
            "BLIBLINXMONOCROMO102.jpg",
            "BLIBLINXMONOCROMO11.jpg",
            "BLIBLINXMONOCROMO13.jpg",
            "BLIBLINXMONOCROMO14.jpg",
            "BLIBLINXMONOCROMO15.jpg",
            "BLIBLINXMONOCROMO16.jpg",
            "BLIBLINXMONOCROMO17.jpg",
            "BLIBLINXMONOCROMO18.jpg",
            "BLIBLINXMONOCROMO19.jpg",
            "BLIBLINXMONOCROMO2.jpg",
            "BLIBLINXMONOCROMO20.jpg",
            "BLIBLINXMONOCROMO21.jpg",
            "BLIBLINXMONOCROMO22.jpg",
            "BLIBLINXMONOCROMO23.jpg",
            "BLIBLINXMONOCROMO25.jpg",
            "BLIBLINXMONOCROMO26.jpg",
            "BLIBLINXMONOCROMO27.jpg",
            "BLIBLINXMONOCROMO28.jpg",
            "BLIBLINXMONOCROMO29.jpg",
            "BLIBLINXMONOCROMO30.jpg",
            "BLIBLINXMONOCROMO31.jpg",
            "BLIBLINXMONOCROMO32.jpg",
            "BLIBLINXMONOCROMO33.jpg",
            "BLIBLINXMONOCROMO34.jpg",
            "BLIBLINXMONOCROMO35.jpg",
            "BLIBLINXMONOCROMO36.jpg",
            "BLIBLINXMONOCROMO37.jpg",
            "BLIBLINXMONOCROMO38.jpg",
            "BLIBLINXMONOCROMO39.jpg",
            "BLIBLINXMONOCROMO4.jpg",
            "BLIBLINXMONOCROMO40.jpg",
            "BLIBLINXMONOCROMO41.jpg",
            "BLIBLINXMONOCROMO42.jpg",
            "BLIBLINXMONOCROMO43.jpg",
            "BLIBLINXMONOCROMO46.jpg",
            "BLIBLINXMONOCROMO47.jpg",
            "BLIBLINXMONOCROMO49.jpg",
            "BLIBLINXMONOCROMO50.jpg",
            "BLIBLINXMONOCROMO51.jpg",
            "BLIBLINXMONOCROMO52.jpg",
            "BLIBLINXMONOCROMO53.jpg",
            "BLIBLINXMONOCROMO54.jpg",
            "BLIBLINXMONOCROMO55.jpg",
            "BLIBLINXMONOCROMO56.jpg",
            "BLIBLINXMONOCROMO57.jpg",
            "BLIBLINXMONOCROMO58.jpg",
            "BLIBLINXMONOCROMO59.jpg",
            "BLIBLINXMONOCROMO60.jpg",
            "BLIBLINXMONOCROMO61.jpg",
            "BLIBLINXMONOCROMO62.jpg",
            "BLIBLINXMONOCROMO63.jpg",
            "BLIBLINXMONOCROMO64.jpg",
            "BLIBLINXMONOCROMO65.jpg",
            "BLIBLINXMONOCROMO66.jpg",
            "BLIBLINXMONOCROMO67.jpg",
            "BLIBLINXMONOCROMO68.jpg",
            "BLIBLINXMONOCROMO69.jpg",
            "BLIBLINXMONOCROMO7.jpg",
            "BLIBLINXMONOCROMO70.jpg",
            "BLIBLINXMONOCROMO71.jpg",
            "BLIBLINXMONOCROMO72.jpg",
            "BLIBLINXMONOCROMO73.jpg",
            "BLIBLINXMONOCROMO74.jpg",
            "BLIBLINXMONOCROMO75.jpg",
            "BLIBLINXMONOCROMO76.jpg",
            "BLIBLINXMONOCROMO77.jpg",
            "BLIBLINXMONOCROMO78.jpg",
            "BLIBLINXMONOCROMO79.jpg",
            "BLIBLINXMONOCROMO8.jpg",
            "BLIBLINXMONOCROMO80.jpg",
            "BLIBLINXMONOCROMO81.jpg",
            "BLIBLINXMONOCROMO82.jpg",
            "BLIBLINXMONOCROMO83.jpg",
            "BLIBLINXMONOCROMO84.jpg",
            "BLIBLINXMONOCROMO85.jpg",
            "BLIBLINXMONOCROMO86.jpg",
            "BLIBLINXMONOCROMO87.jpg",
            "BLIBLINXMONOCROMO88.jpg",
            "BLIBLINXMONOCROMO89.jpg",
            "BLIBLINXMONOCROMO90.jpg",
            "BLIBLINXMONOCROMO91.jpg",
            "BLIBLINXMONOCROMO92.jpg",
            "BLIBLINXMONOCROMO93.jpg",
            "BLIBLINXMONOCROMO94.jpg",
            "BLIBLINXMONOCROMO95.jpg",
            "BLIBLINXMONOCROMO96.jpg",
            "BLIBLINXMONOCROMO97.jpg",
            "BLIBLINXMONOCROMO98.jpg",
            "BLIBLINXMONOCROMO99.jpg",
        ]
    },
    {
        nombre: "ONLYLOCALS",
        lugar: "MyClub, Santiago",
        carpeta: "MYCLUB_onlylocals_06_25",
        fotos: [
            "IMG_3400.jpg",
            "IMG_3420.jpg",
            "IMG_3421.jpg",
            "IMG_3423.jpg",
            "IMG_3425.jpg",
            "IMG_3426.jpg",
            "IMG_3428.jpg",
            "IMG_3429.jpg",
            "IMG_3431.jpg",
            "IMG_3432.jpg",
            "IMG_3434.jpg",
            "IMG_3437.jpg",
            "IMG_3440.jpg",
            "IMG_3442.jpg",
            "IMG_3444.jpg",
            "IMG_3445.jpg",
            "IMG_3447.jpg",
            "IMG_3449.jpg",
            "IMG_3452.jpg",
            "IMG_3456.jpg",
            "IMG_3458.jpg",
            "IMG_3460.jpg",
            "IMG_3462.jpg",
            "IMG_3466.jpg",
            "IMG_3467.jpg",
            "IMG_3473.jpg",
            "IMG_3476.jpg",
            "IMG_3480.jpg",
            "IMG_3482.jpg",
            "IMG_3484.jpg",
            "IMG_3485.jpg",
            "IMG_3489.jpg",
            "IMG_3490.jpg",
            "IMG_3491.jpg",
            "IMG_3494.jpg",
            "IMG_3495.jpg",
            "IMG_3498.jpg",
        ]
    },
    {
        nombre: "SUPERRESERVAO",
        lugar: "MyClub, Santiago",
        carpeta: "MYCLUB_superreservao_04_11_25",
        fotos: [
            "IMG_2479.jpg",
            "IMG_2481.jpg",
            "IMG_2484.jpg",
            "IMG_2487.jpg",
            "IMG_2489.jpg",
            "IMG_2491.jpg",
            "IMG_2493.jpg",
            "IMG_2495.jpg",
            "IMG_2496.jpg",
            "IMG_2499.jpg",
            "IMG_2501.jpg",
            "IMG_2502.jpg",
            "IMG_2505.jpg",
            "IMG_2510.jpg",
            "IMG_2512.jpg",
            "IMG_2513.jpg",
            "IMG_2515.jpg",
            "IMG_2523.jpg",
            "IMG_2524.jpg",
            "IMG_2528.jpg",
            "IMG_2532.jpg",
            "IMG_2533.jpg",
            "IMG_2536.jpg",
            "IMG_2542.jpg",
            "IMG_2543.jpg",
            "IMG_2546.jpg",
            "IMG_2556.jpg",
            "IMG_2557.jpg",
            "IMG_2568.jpg",
            "IMG_2571.jpg",
            "IMG_2572.jpg",
            "IMG_2577.jpg",
            "IMG_2582.jpg",
            "IMG_2586.jpg",
            "IMG_2589.jpg",
            "IMG_2590.jpg",
            "IMG_2592.jpg",
            "IMG_2598.jpg",
            "IMG_2617.jpg",
            "IMG_2619.jpg",
            "IMG_2626.jpg",
            "IMG_2629.jpg",
            "IMG_2632.jpg",
            "IMG_2633.jpg",
            "IMG_2634.jpg",
            "IMG_2637.jpg",
            "IMG_2638.jpg",
            "IMG_2640.jpg",
            "IMG_2642.jpg",
            "IMG_2647.jpg",
            "IMG_2648.jpg",
            "IMG_2649.jpg",
            "IMG_2652.jpg",
            "IMG_2654.jpg",
            "IMG_2656.jpg",
            "IMG_2658.jpg",
            "IMG_2659.jpg",
            "IMG_2661.jpg",
            "IMG_2664.jpg",
            "IMG_2666.jpg",
            "IMG_2673.jpg",
            "IMG_2683.jpg",
            "IMG_2686.jpg",
            "IMG_2687.jpg",
            "IMG_2694.jpg",
            "IMG_2695.jpg",
            "IMG_2696.jpg",
            "IMG_2697.jpg",
            "IMG_2698.jpg",
            "IMG_2699.jpg",
            "IMG_2700.jpg",
            "IMG_2702.jpg",
            "IMG_2704.jpg",
            "IMG_2705.jpg",
            "IMG_2706.jpg",
            "IMG_2709.jpg",
            "IMG_2710.jpg",
            "IMG_2712.jpg",
            "IMG_2713.jpg",
            "IMG_2716.jpg",
            "IMG_2724.jpg",
            "IMG_2725.jpg",
            "IMG_2726.jpg",
            "IMG_2727.jpg",
            "IMG_2729.jpg",
            "IMG_2732.jpg",
            "IMG_2733.jpg",
            "IMG_2734.jpg",
            "IMG_2735.jpg",
            "IMG_2737.jpg",
            "IMG_2738.jpg",
            "IMG_2739.jpg",
            "IMG_2740.jpg",
            "IMG_2741.jpg",
            "IMG_2742.jpg",
            "IMG_2748.jpg",
            "IMG_2750.jpg",
            "IMG_2751.jpg",
            "IMG_2752.jpg",
            "IMG_2755.jpg",
            "IMG_2756.jpg",
            "IMG_2757.jpg",
            "IMG_2758.jpg",
            "IMG_2759.jpg",
            "IMG_2762.jpg",
            "IMG_2764.jpg",
            "IMG_2765.jpg",
            "IMG_2767.jpg",
            "IMG_2768.jpg",
            "IMG_2772.jpg",
            "IMG_2773.jpg",
            "IMG_2777.jpg",
            "IMG_2781.jpg",
            "IMG_2788.jpg",
            "IMG_2790.jpg",
            "IMG_2792.jpg",
            "IMG_2793.jpg",
            "IMG_2796.jpg",
            "IMG_2797.jpg",
            "IMG_2800.jpg",
            "IMG_2802.jpg",
            "IMG_2803.jpg",
            "IMG_2804.jpg",
            "IMG_2806.jpg",
            "IMG_2807.jpg",
            "IMG_2808.jpg",
            "IMG_2812.jpg",
            "IMG_2813.jpg",
            "IMG_2816.jpg",
            "IMG_2825.jpg",
            "IMG_2826.jpg",
        ]
    },
    {
        nombre: "VANITAS",
        lugar: "Vanitas, Santiago",
        carpeta: "VANITAS_02_10_25",
        fotos: [
            "IMG_3681.jpg",
            "IMG_3684.jpg",
            "IMG_3686.jpg",
            "IMG_3690.jpg",
            "IMG_3696.jpg",
            "IMG_3700.jpg",
            "IMG_3703.jpg",
            "IMG_3704.jpg",
            "IMG_3706.jpg",
            "IMG_3707.jpg",
            "IMG_3710.jpg",
            "IMG_3712.jpg",
            "IMG_3713.jpg",
            "IMG_3715.jpg",
            "IMG_3717.jpg",
            "IMG_3724.jpg",
            "IMG_3727.jpg",
            "IMG_3730.jpg",
            "IMG_3732.jpg",
            "IMG_3734.jpg",
            "IMG_3735.jpg",
            "IMG_3738.jpg",
            "IMG_3740.jpg",
            "IMG_3741.jpg",
            "IMG_3742.jpg",
            "IMG_3744.jpg",
            "IMG_3746.jpg",
            "IMG_3748.jpg",
            "IMG_3749.jpg",
            "IMG_3751.jpg",
            "IMG_3754.jpg",
            "IMG_3759.jpg",
            "IMG_3762.jpg",
            "IMG_3763.jpg",
            "IMG_3768.jpg",
            "IMG_3770.jpg",
            "IMG_3772.jpg",
            "IMG_3779.jpg",
            "IMG_3780.jpg",
            "IMG_3788.jpg",
            "IMG_3790.jpg",
            "IMG_3794.jpg",
            "IMG_3803.jpg",
            "IMG_3805.jpg",
            "IMG_3806.jpg",
            "IMG_3807.jpg",
            "IMG_3810.jpg",
            "IMG_3811.jpg",
            "IMG_3817.jpg",
            "IMG_3819.jpg",
            "IMG_3820.jpg",
            "IMG_3822.jpg",
            "IMG_3824.jpg",
            "IMG_3825.jpg",
            "IMG_3827.jpg",
            "IMG_3831.jpg",
            "IMG_3835.jpg",
            "IMG_3838.jpg",
            "IMG_3840.jpg",
            "IMG_3844.jpg",
            "IMG_3853.jpg",
            "IMG_3855.jpg",
            "IMG_3859.jpg",
            "IMG_3872.jpg",
            "IMG_3874.jpg",
            "IMG_3876.jpg",
            "IMG_3881.jpg",
            "IMG_3883.jpg",
            "IMG_3885.jpg",
            "IMG_3887.jpg",
            "IMG_3892.jpg",
            "IMG_3894.jpg",
            "IMG_3901.jpg",
            "IMG_3911.jpg",
            "IMG_3914.jpg",
            "IMG_3917.jpg",
            "IMG_3927.jpg",
            "IMG_3936.jpg",
            "IMG_3937.jpg",
            "IMG_3942.jpg",
            "IMG_3944.jpg",
            "IMG_3946.jpg",
            "IMG_3947.jpg",
            "IMG_3949.jpg",
            "IMG_3954.jpg",
            "IMG_3957.jpg",
            "IMG_3960.jpg",
            "IMG_3963.jpg",
            "IMG_3964.jpg",
            "IMG_3968.jpg",
            "IMG_3974.jpg",
            "IMG_3975.jpg",
        ]
    },
    {
        nombre: "VARIADAS",
        lugar: "",
        carpeta: "variadas",
        fotos: [
            "IMG_0.jpg",
            "IMG_1.jpg",
            "IMG_1304.jpg",
            "IMG_1307.jpg",
            "IMG_1309.jpg",
            "IMG_1310.jpg",
            "IMG_1311.jpg",
            "IMG_1312.jpg",
            "IMG_1315.jpg",
            "IMG_1316.jpg",
            "IMG_1317.jpg",
            "IMG_1318.jpg",
            "IMG_1320.jpg",
            "IMG_1661.jpg",
            "IMG_1662.jpg",
            "IMG_1663.jpg",
            "IMG_1664.jpg",
            "IMG_1665.jpg",
            "IMG_1666.jpg",
            "IMG_1667.jpg",
            "IMG_1668.jpg",
            "IMG_1669.jpg",
            "IMG_1670.jpg",
            "IMG_1672.jpg",
            "IMG_1673.jpg",
            "IMG_3.jpg",
        ]
    },
];

const contenedor = document.getElementById("fiestas-galeria");

// Si el contenedor tiene data-carpeta, solo mostramos esa fiesta.
// Si no lo tiene, mostramos todas.
const carpetaSolicitada = contenedor?.dataset.carpeta;

const fiestasAMostrar = carpetaSolicitada
    ? fiestas.filter(f => f.nombre.trim().toLowerCase() === carpetaSolicitada.trim().toLowerCase())
    : fiestas;

if (carpetaSolicitada && fiestasAMostrar.length === 0) {
    console.warn(`No se encontró ninguna fiesta con nombre "${carpetaSolicitada}" en galeria.js`);
}

fiestasAMostrar.forEach(fiesta => {
    const seccion = document.createElement("section");
    seccion.className = "galeria-fiesta";

    const titulo = document.createElement("h2");
    titulo.textContent = fiesta.nombre;

    const lugar = document.createElement("p");
    lugar.textContent = fiesta.lugar;

    const grid = document.createElement("div");
    grid.className = "gallery-grid";

    fiesta.fotos.forEach(foto => {
        const img = document.createElement("img");

        img.src = `${R2_PUBLIC_URL}/imagenes/fiestas/${fiesta.carpeta}/${foto}`;
        img.alt = `Monocromatics ${fiesta.nombre}`;
        img.loading = "lazy";

        img.addEventListener("click", () => abrirFoto(img.src));

        grid.appendChild(img);
    });

    seccion.appendChild(titulo);
    seccion.appendChild(lugar);
    seccion.appendChild(grid);
    contenedor.appendChild(seccion);
});

function abrirFoto(src) {
    const visor = document.createElement("div");
    visor.className = "visor-foto";

    const botonCerrar = document.createElement("button");
    botonCerrar.type = "button";
    botonCerrar.className = "cerrar-visor";
    botonCerrar.textContent = "×";

    const imagen = document.createElement("img");
    imagen.src = src;
    imagen.alt = "Foto Monocromatics";

    const descargar = document.createElement("a");
    descargar.href = src;
    descargar.download = "";
    descargar.className = "descargar-foto";
    descargar.textContent = "DESCARGAR";

    visor.appendChild(botonCerrar);
    visor.appendChild(imagen);
    visor.appendChild(descargar);

    document.body.appendChild(visor);

    function cerrarVisor() {
        visor.remove();
        document.removeEventListener("keydown", cerrarConEscape);
    }

    function cerrarConEscape(e) {
        if (e.key === "Escape") {
            cerrarVisor();
        }
    }

    document.addEventListener("keydown", cerrarConEscape);

    visor.querySelector(".cerrar-visor").addEventListener("click", cerrarVisor);

    visor.addEventListener("click", e => {
        if (e.target === visor) {
            cerrarVisor();
        }
    });
}

